# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170118_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=18, null=True, validators=[main.validators.PhoneValidator()], verbose_name='phone'),
        ),
    ]
