# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170118_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='The format of phone numbers is +7 (123) 456-78-90', max_length=18, null=True, validators=[main.validators.PhoneValidator()], verbose_name='phone'),
        ),
    ]
