# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170118_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Invite code')),
                ('status', models.CharField(choices=[('WT', 'Waiting'), ('AP', 'Approved'), ('DC', 'Declined')], default='WT', max_length=2, verbose_name='Status')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='Child')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Invited user')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='Relative')),
            ],
            options={
                'verbose_name_plural': 'Family relatives',
                'verbose_name': 'Family relative',
            },
        ),
    ]
