# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='request',
            field=models.CharField(choices=[('WT', 'Waiting'), ('AP', 'Approved'), ('DC', 'Declined')], default='WT', max_length=2, verbose_name='Relationship request'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.TextField(verbose_name='Relationship status'),
        ),
    ]
