# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20170314_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='invited_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Invited user'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relative',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='Relative'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.TextField(default='', verbose_name='Relationship status'),
        ),
    ]
