# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20170314_2041'),
        ('userprofile', '0005_auto_20170409_1343'),
    ]

    operations = [
    ]
