# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_merge_20170415_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='status',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relative',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
    ]
