# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20170415_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='code',
        ),
    ]
