# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_remove_relationship_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='Use contents of this field instead of username', max_length=250, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.BooleanField(default=True, help_text='Enable user profile and social/personal actions', verbose_name='Account is personal'),
        ),
    ]
