# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20170417_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='confirmation_code',
            field=models.CharField(default=None, max_length=8, null=True, verbose_name='Confirmation code'),
        ),
    ]
