# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_relationship_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='confirmation_code',
            field=models.CharField(db_index=True, default=None, max_length=8, null=True, verbose_name='Confirmation code'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='invited_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Invited user'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relative',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='valid_until',
            field=models.DateTimeField(db_index=True, default=None, null=True, verbose_name='Valid until'),
        ),
    ]
