# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 18:20
from __future__ import unicode_literals

from django.contrib.auth.models import Group, Permission
from django.db import migrations


# get Permission object by codename, usually it a '<action>_<modelname>'
def create_permissions(permissions_list, model_name):
    return [Permission.objects.get(codename="{}_{}".format(permission, model_name)) for permission in permissions_list]


def create_groups(app, schema_editor):
    import logging
    group, created = Group.objects.get_or_create(name='campVoucherCommittee')

    if created:
        permissions = create_permissions(['add', 'change', 'delete', 'view'], 'campvoucher')
        for permission in permissions:
            group.permissions.add(permission)
    else:
        logging.error('Cannot create group for admins!')


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
