# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
