# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(max_length=30, verbose_name='Номер путёвки')),
                ('status', models.CharField(choices=[('WP', 'Ожидает оплаты'), ('DC', 'Отклонено'), ('PD', 'Оплачено'), ('AP', 'Подтверждено')], default='WP', max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Путёвка',
                'verbose_name_plural': 'Путёвки',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('begin', models.DateTimeField(verbose_name='Начало обучения')),
                ('end', models.DateTimeField(verbose_name='Окончание обучения')),
                ('registration_begin', models.DateTimeField(verbose_name='Начало регистрации')),
                ('registration_end', models.DateTimeField(verbose_name='Окончание регистрации')),
            ],
            options={
                'verbose_name': 'Период обучения',
                'verbose_name_plural': 'Периоды обучения',
            },
        ),
        migrations.AddField(
            model_name='campvoucher',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Period', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='campvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец путёвки'),
        ),
    ]
