# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvoucher',
            options={'permissions': (('view_campvoucher', 'Возможность просматривать путевки'),), 'verbose_name': 'Путёвка', 'verbose_name_plural': 'Путёвки'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'permissions': (('view_period', 'Возможность просматривать периоды обучения'),), 'verbose_name': 'Период обучения', 'verbose_name_plural': 'Периоды обучения'},
        ),
    ]
