# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('begin', models.DateTimeField(verbose_name='Начало события')),
                ('end', models.DateTimeField(verbose_name='Окончание события')),
                ('registration_begin', models.DateTimeField(verbose_name='Начало регистрации')),
                ('registration_end', models.DateTimeField(verbose_name='Окончание регистрации')),
                ('is_open', models.BooleanField(verbose_name='Регистрация открыта')),
                ('limit', models.IntegerField(verbose_name='Максимальное количество участников')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Period', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
