# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CL', 'Учебная группа'), ('CA', 'Отряд'), ('OL', 'Турнир')], default='CL', max_length=2, verbose_name='Тип события'),
        ),
    ]
