# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20170108_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvoucher',
            options={'verbose_name': 'Camp voucher', 'verbose_name_plural': 'Camp vouchers'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventapplication',
            options={'verbose_name': 'Event application', 'verbose_name_plural': 'Event applications'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterField(
            model_name='campvoucher',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='campvoucher',
            name='status',
            field=models.CharField(choices=[('WP', 'Awaiting payment'), ('DC', 'Declined'), ('PD', 'Paid'), ('AP', 'Approved')], default='WP', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='campvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Voucher owner'),
        ),
        migrations.AlterField(
            model_name='campvoucher',
            name='voucher_id',
            field=models.CharField(max_length=30, verbose_name='Voucher ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='begin',
            field=models.DateTimeField(verbose_name='Event begins'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='Event ends'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(verbose_name='Registration open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(verbose_name='Participants limit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_begin',
            field=models.DateTimeField(verbose_name='Registration begins'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(verbose_name='Registration ends'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CL', 'Class group'), ('CA', 'Camp group'), ('OL', 'Tournament')], default='CL', max_length=2, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('TG', 'Testing'), ('TS', 'Testing succeeded'), ('ST', 'Studying'), ('SC', 'Successed'), ('FL', 'Failed'), ('DQ', 'Disqualified')], default='TG', max_length=2, verbose_name='Application status'),
        ),
        migrations.AlterField(
            model_name='period',
            name='begin',
            field=models.DateTimeField(verbose_name='Period begins'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end',
            field=models.DateTimeField(verbose_name='Period ends'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='period',
            name='registration_begin',
            field=models.DateTimeField(verbose_name='Registration begins'),
        ),
        migrations.AlterField(
            model_name='period',
            name='registration_end',
            field=models.DateTimeField(verbose_name='Registration ends'),
        ),
    ]
