# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20170109_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campvoucher',
            options={'permissions': (('view_campvoucher', 'view camp vouchers'),), 'verbose_name': 'Camp voucher', 'verbose_name_plural': 'Camp vouchers'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'permissions': (('view_period', 'view periods'),), 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
    ]
