# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_auto_20170109_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rand_problems', models.IntegerField(verbose_name='Random problems')),
                ('slot_problems', models.IntegerField(verbose_name='Slot problems')),
                ('min_score', models.IntegerField(verbose_name='Minimum total score')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.Event')),
            ],
            options={
                'verbose_name': 'Practice exam',
                'verbose_name_plural': 'Practice exams',
            },
        ),
        migrations.CreateModel(
            name='PracticeExamApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExam')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeExamApplicationProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExamApplication')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='PracticeExamProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Problem name')),
                ('ejudge_id', models.CharField(max_length=100, unique=True, verbose_name='Problem id')),
                ('slot', models.IntegerField(verbose_name='Problem slot')),
                ('statement_url', models.CharField(max_length=500, verbose_name='Statement URL')),
                ('score', models.IntegerField(verbose_name='Problem score')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExam')),
            ],
            options={
                'verbose_name': 'Practice exam problem',
                'verbose_name_plural': 'Practice exams problems',
            },
        ),
        migrations.CreateModel(
            name='PracticeExamRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejudge_run_id', models.IntegerField(unique=True, verbose_name='Run ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExamProblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice exam run',
                'verbose_name_plural': 'Practice exams runs',
            },
        ),
        migrations.AddField(
            model_name='practiceexamapplicationproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExamProblem'),
        ),
        migrations.AddField(
            model_name='practiceexamapplication',
            name='problems',
            field=models.ManyToManyField(through='applications.PracticeExamApplicationProblem', to='applications.PracticeExamProblem'),
        ),
        migrations.AddField(
            model_name='practiceexamapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='practice_exam',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExamApplication'),
        ),
    ]
