# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20170110_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceexamapplication',
            name='practice_exam',
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='practice_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExamApplication'),
        ),
    ]
