# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20170110_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Home address'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='school',
            field=models.CharField(max_length=50, null=True, verbose_name='School'),
        ),
    ]
