# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20170111_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='practice_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.PracticeExamApplication'),
        ),
    ]
