# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20170111_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceexamrun',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Submitted at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], help_text='Current grade', null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='phone',
            field=models.CharField(help_text='Phone number like +7 (123) 456 78 90', max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='school',
            field=models.CharField(help_text='e.g. School №42', max_length=50, null=True, verbose_name='School'),
        ),
    ]
