# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20170113_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryexamquestion',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
