# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_theoryexamquestion_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryexamapplicationquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
