# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_theoryexamapplicationquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryexamquestion',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
