# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_theoryexamquestion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='practice_exam',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='theory_exam',
        ),
        migrations.AddField(
            model_name='practiceexamapplication',
            name='application',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='practice_exam', to='applications.EventApplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryexamapplication',
            name='application',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='theory_exam', to='applications.EventApplication'),
            preserve_default=False,
        ),
    ]
