# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20170118_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventapplication',
            options={'permissions': (('can_submit_application', 'Can submit applications to the study period'),), 'verbose_name': 'Event application', 'verbose_name_plural': 'Event applications'},
        ),
    ]
