# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20170404_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metatype',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Meta type'),
        ),
    ]
