# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_event_metatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='metatype',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category'),
        ),
    ]
