# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20170406_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theoryexamquestion',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
