# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20170408_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceexamproblem',
            name='statement_url',
        ),
        migrations.AddField(
            model_name='practiceexamproblem',
            name='statement',
            field=models.FileField(blank=True, upload_to='', verbose_name='Statement'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='phone',
            field=models.CharField(help_text='The format of phone numbers is +7 (123) 456-78-90', max_length=18, null=True, validators=[main.validators.PhoneValidator()], verbose_name='Phone number'),
        ),
    ]
