# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20170409_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('TG', 'Testing'), ('TS', 'Testing succeeded'), ('TF', 'Testing failed'), ('ER', 'Enrolled'), ('ST', 'Studying'), ('SC', 'Successed'), ('FL', 'Failed'), ('DQ', 'Disqualified')], default='TG', max_length=2, verbose_name='Application status'),
        ),
    ]
