# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20170410_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='difficulty',
            field=models.IntegerField(default=0, verbose_name='Relative difficulty'),
        ),
    ]
