# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_event_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='confirm_participation',
            field=models.BooleanField(default=False, verbose_name='Confirm participation'),
        ),
    ]
