# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_eventapplication_confirm_participation'),
        ('applications', '0018_auto_20170118_2321'),
    ]

    operations = [
    ]
