# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_merge_20170415_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='phone',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='parent_phone_numbers',
            field=models.TextField(blank=True, null=True, verbose_name="Parents' phone numbers"),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='personal_data_doc',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Personal data processing agreement'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Home address'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], help_text='Current grade', null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='school',
            field=models.CharField(blank=True, help_text='e.g. School №42', max_length=50, null=True, verbose_name='School'),
        ),
    ]
