# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_auto_20170415_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventapplication',
            options={'verbose_name': 'Event application', 'verbose_name_plural': 'Event applications'},
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='address',
            field=models.TextField(null=True, verbose_name='Home address'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], help_text='Current grade', null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='personal_data_doc',
            field=models.ImageField(null=True, upload_to='', verbose_name='Personal data processing agreement'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='school',
            field=models.CharField(help_text='e.g. School №42', max_length=50, null=True, verbose_name='School'),
        ),
    ]
