# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_auto_20170416_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campvoucher',
            name='period',
        ),
        migrations.RemoveField(
            model_name='campvoucher',
            name='user',
        ),
        migrations.DeleteModel(
            name='CampVoucher',
        ),
    ]
