# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_auto_20170417_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='voucher_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Voucher ID'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='voucher_parent',
            field=models.CharField(help_text='Full name of the parent to whom the voucher is drawn up', max_length=250, null=True, verbose_name="Parent's full name"),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='personal_data_doc',
            field=models.FileField(null=True, upload_to='', verbose_name='Personal data processing agreement'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('TG', 'Testing'), ('AC', 'Accepted'), ('TF', 'Testing failed'), ('ER', 'Enrolled'), ('IS', 'Issued'), ('ST', 'Studying'), ('SC', 'Successed'), ('FL', 'Failed'), ('DQ', 'Disqualified')], default='TG', max_length=2, verbose_name='Application status'),
        ),
    ]
