# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20170417_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='personal_laptop',
            field=models.BooleanField(default=False, verbose_name='Personal laptop will be used'),
        ),
    ]
