# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0031_eventapplication_personal_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='issued_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Issued'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='issued_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_applications', related_query_name='issued_application', to=settings.AUTH_USER_MODEL, verbose_name='Issued by'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='submitted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Submitted'),
        ),
    ]
