# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_periodattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodattachment',
            name='type',
            field=models.CharField(choices=[('AG', 'Personal data processing agreement'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Attachment type'),
        ),
    ]
