# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_eventapplication_denial_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('TG', 'Testing'), ('AC', 'Accepted'), ('TF', 'Testing failed'), ('DE', 'Denied'), ('ER', 'Enrolled'), ('IS', 'Issued'), ('ST', 'Studying'), ('SC', 'Successed'), ('FL', 'Failed'), ('DQ', 'Disqualified')], default='TG', max_length=2, verbose_name='Application status'),
        ),
    ]
