# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0038_auto_20170502_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(related_name='coordinated_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
