# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20170504_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='school',
        ),
    ]
