# DATABASE CONFIGURATION
# options: sqlite3, postgresql, mysql
DATABASE_ENGINE = "sqlite3"

# db name / sqlite db file
DATABASE_NAME = "db.sqlite3"

DATABASE_USER = ""
DATABASE_PASSWORD = ""
DATABASE_HOST = ""
DATABASE_PORT = ""

# EJUDGE CONFIGURATION

EJUDGE_CONTEST_ID = 1
EJUDGE_USER_LOGIN = "ejudge"
EJUDGE_USER_PASSWORD = "ejudge"