# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170108_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'News post', 'verbose_name_plural': 'News posts'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='Posted at'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='modified',
            field=models.DateTimeField(verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitted user'),
        ),
    ]
