# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170108_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'permissions': (('view_period', 'Возможность просматривать новости'),), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
