# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170109_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'permissions': (('view_news', 'view news'),), 'verbose_name': 'News post', 'verbose_name_plural': 'News posts'},
        ),
    ]
